version = "0.5.0"
content_dir = "content"

[pdf.spine]
title = "Digital Theory Lab"
merge = true
exclude = ["data/events.typ", "data/people.typ", "site.typ"]

[epub.spine]
title = "Digital Theory Lab"
exclude = ["data/events.typ", "data/people.typ", "site.typ"]
